version: '3.8'

services:
  email-verifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
    networks:
      - email-verifier-network

  # Optional: Add a simple web server to serve the test page
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./test_api.html:/usr/share/nginx/html/test_api.html
    depends_on:
      - email-verifier
    networks:
      - email-verifier-network

networks:
  email-verifier-network:
    driver: bridge
